### ISSUE TITLE
Duplicate objects returned back after piping to Invoke-CCMBaseline

### ISSUE THREAD

**Issue by codaamok** [CodyMathis123/PSCCMClient#48]
A picture says a thousand words :-)

![image](https://user-images.githubusercontent.com/6683266/90642538-6b01b800-e22a-11ea-8ee2-b55a858af119.png)

**Comment by CodyMathis123** [comment]
This is resolved in 0.3.1

If you had multiple CIMSessions or PSSessions open to a PC, they were all found when Get-CCMConnection ran.

This could be seen by running with -verbose. We now select the first one found to ensure only one CIMSession or PSSession is used.
